runtime: openjdk LLVM-i386 under nix
trailofbits/sholva pull request #161
Opened 2023-06-05 16:38 UTC by jleightcap

2023-06-05 16:41 UTC, jleightcap commented on test/log4shell/.gitignore
(these files are deleted, later moved on top of the nix derivation.)

2023-06-05 16:46 UTC, jleightcap commented on test/Makefile
Adding debug symbols to assembling/compiling rules.

2023-06-16 16:36 UTC, lisaoverall requested changes
LGTM -

2023-06-16 17:07 UTC, lisaoverall approved these changes

2023-06-16 17:49 UTC, merged