[WIP] jleightcap/syscall skeletal syscall structure.
trailofbits/sholva pull request #82
Opened 2022-09-21 14:46 UTC by jleightcap

2022-09-21 14:49 UTC, jleightcap commented on circuit/execute/alu.v
>  module alu
clash target compilation frequently changes for unchanged source. i'm guessing this is nix pulling in a dev branch of clash, but i haven't investigated.

2022-09-21 14:54 UTC, jleightcap commented on circuit/execute/alu.v
>  module alu
(in hindsight, this shouldn't be checked in. going to leave this and `syscall.v` for this PR in making the integration clearer.)

2022-10-26 04:26 UTC, jleightcap commented on circuit/execute/alu.v.old
> -`include "defines.v"
this may or may not be worth keeping around.

2022-10-26 14:29 UTC, jleightcap commented
@woodruffw some expository text for 2022-10-26 review.

from verification up to syscalls,
1. previously the `check.v` `step1 -> step2` was verified by asserting all registers equal, now additionally verifies the step1's syscall state is computed to be step2's syscall state (tiny86 output `o_syscall_state` == `n_syscall_state`)
2. step structure is augmented with syscall state. the major structural decision i want to get feedback on,
  - 560bit step; contains 2x `hint :: {meta :: 1 byte, address :: 4 byte, data :: 4 byte}`.
  - augment that `meta` field of _both hints in the step_ to encode state -- concatenate the 4 unused bits in each hint's `meta` field to encode an 8-bit state.
  - so, `meta :: {valid :: 1 bit, syscall_state :: 4 bit, r/w :: 1 bit, mask :: 2 bit}`. then, `wire [7:0] syscall_state <- {meta_1[6:3], meta_2[6:3]}`.
  - this is... unnecessary; certainly aren't encoding a 256-state DFA. however, it's consistent with my next point...
3. i'm working with the assumption here that the syscall DFA transitions work over _steps_, not _hints_; that is, every syscall transition has a 1:1 correspondence to a step (2x hints).
  - this was kind of subtle to me. in the case of say, a 10-byte `transmit` syscall, that only requires 5 _hints_.
  - my working assumption here is that the tracer will 'pad' appropriately (effectively just slot in either a NOP hint or set the `meta`'s `valid` bit to `0`... but have it still encode state. unsure.)
  
(in meetings, will continue comment if i'm done before you get to this.)

2022-10-26 19:40 UTC, jleightcap commented
re: register file updates during syscall execution, per [INTEL 80386 PROGRAMMER'S REFERENCE MANUAL 1986](https://css.csail.mit.edu/6.858/2014/readings/i386.pdf)p307

```
REAL-ADDRESS-MODE:
 Push (FLAGS);
 IF ← 0; (* Clear interrupt flag *)
 TF ← 0; (* Clear trap flag *)
 Push(CS);
 Push(IP);
 (* No error codes are pushed *)
 CS ← IDT[Interrupt number * 4].selector;
 IP ← IDT[Interrupt number * 4].offset;
```

with these side-car syscall DFAs of course don't care about like, calling convention and storing state on the stack.
but, i get the impression from this that `FLAGS` and `IP` are the only 2 registers preserved across a syscall boundary.

2022-10-26 20:26 UTC, woodruffw commented
> but, i get the impression from this that `FLAGS` and `IP` are the only 2 registers preserved across a syscall boundary.

Yep, from the CPU's perspective. From the guest program's perspective, the kernel may choose to preserve/communicate state via registers as well. In general, for Linux on x86, EAX is used for the return value and all other registers are non-volatile, meaning that they shouldn't change.

2022-10-26 20:26 UTC, woodruffw commented
> * termination on '\0' (find this in msp430 implementation)

FWIW, I don't think we want this for the DECREE syscalls -- I don't believe `receive` terminates on `\0` (although I could be wrong).

2022-10-27 14:13 UTC, woodruffw commented on circuit/codegen/encodings.spec
> +CMD_INT:CD+ib~I~r
Encoding looks correct here!

2022-10-27 14:14 UTC, woodruffw reviewed
LGTM overall; I assume we're going to need changes to the tracer to get the CI passing, right?

2022-10-27 21:27 UTC, jleightcap commented on check.v
> +`default_nettype none
23.2.2.3 Rules for determining port kind, data type, and direction

> For the first port in an ANSI style port list:
> 
> If the port kind is omitted:
> For input and inout ports, the port shall default to a net of default net type. The default net type can be changed using the `default_nettype compiler directive

verilog lets you get away with using some undeclared things by default, just set those to error

this should probably be at the header of all `.v`, just added here while in development.

2022-10-27 21:31 UTC, woodruffw commented on check.v
> +`default_nettype none
Makes sense, thanks for the explanation. Yeah, let's put this everywhere.

2023-02-17 21:10 UTC, lisaoverall commented on mttn/src/tiny86.rs
> +    const SERIALIZED_SIZE: usize = (8 * 4) + (3 * 4) + 4 + 4;
Thanks for breaking this out so it's clearly related to the comment above.

2023-02-17 21:27 UTC, lisaoverall commented on mttn/src/syscall.rs
> +        match syscall {
Long term, we may want to reconsider whether we should translate to the DecreeSyscall model as in trace.rs, but this should be fine for now.

2023-02-17 21:32 UTC, lisaoverall commented on tiny86/src/Syscall.hs
> +        SYSCALL_TERMINATE -> todo
Why is `terminate` still marked todo when it is implemented in the DecreeSyscall model in syscall.rs?

2023-02-17 21:36 UTC, lisaoverall commented on tiny86/src/Syscall/Internal.hs
> +instance Enum Syscall where
Again, in future, perhaps we should revisit the choice of using the DECREE syscall model here, but should be fine for now.

2023-02-17 21:44 UTC, lisaoverall commented on tiny86/src/Syscall/Read.hs
> +syscallReadDFA :: SyscallDFA
I think I understand this after comparing against Receive.hs, but would you be able to add some comments explaining each case?

2023-02-17 21:51 UTC, lisaoverall requested changes
Thanks, this looks great! I left a few comments/questions on individual files. We still need to to go through and make sure `recieve` becomes `receive` everywhere 😉 - I have to step away for a few hours, but I can take care of it before the end of the night if you're out for the week.

2023-02-18 13:51 UTC, lisaoverall approved these changes

2023-02-18 13:52 UTC, merged